services:

  db:
    image: postgres:latest
    restart: always
    hostname: db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data


  server:
    container_name: server
    build:
      context: ./server
    ports:
      - "8001:8001"

  app:
    container_name: app
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      SERVER_URL: ${SERVER_URL}
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_ECHO: ${DB_ECHO}
    healthcheck:
      test: [ "CMD-SHELL", "curl -x POST -F 'data=None' http://server:8001/ping" ]
    depends_on:
      db:
        condition: service_healthy
