version: '3.8'

services:

  db:
    image: postgres:latest
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 1234:5432


  server:
    container_name: server
    build:
      context: ./server
    ports:
      - "8001:8001"

  app:
    container_name: app
    build:
      context: ./src
    ports:
      - "8000:8000"
    environment:
      SERVER_URL: ${SERVER_URL}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_ECHO: ${DB_ECHO}
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://server:8001/" ]
    depends_on:
      db:
        condition: service_healthy
